sudo: required

branches:
  only:
    - master

env:
  DOCKER_IMAGE=smatyas/helm-kubectl-plus
  DOCKER_TAG=2.15.2

services:
  - docker

script:
  - docker build --build-arg BASE_TAG=$DOCKER_TAG -t $DOCKER_IMAGE:$DOCKER_TAG .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_IMAGE:$DOCKER_TAG
